### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jose-pr** [jose-pr/sywac#1]
- [ ] Convert buffer to ts
- [ ] Convert utils to ts or get typings for it
- [ ] Create Generic Base interface for all types IType<T> 
- [ ] Create Generic IFactory<T,O> where T is created type and O is options
- [ ] Add Documentation to public methods
- [ ] Ignore private on generated d.ts and docs
- [ ] Api methods should return modified Api with argument type added to it.
- [ ] Function Methods for handlers typings
